# Generated by Django 3.2.22 on 2023-10-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('ON PROCESS', 'On Process'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='TODO', max_length=15),
        ),
    ]
