# Generated by Django 3.2.22 on 2023-10-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('journal', '0002_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_todo', to='user_profile.userprofile'),
        ),
    ]
