# Generated by Django 3.2.22 on 2023-10-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_todo_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('ON PROCESS', 'On Process'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived'), ('DONE', 'Done')], default='TODO', max_length=15),
        ),
    ]
