# Generated by Django 3.2.22 on 2023-11-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_todo_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DairyLapse',
            new_name='DiaryLapse',
        ),
    ]
