# Generated by Django 3.2.22 on 2023-11-06 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_mood_emoji'),
        ('journal', '0005_rename_dairylapse_diarylapse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_diary', to='user_profile.userprofile'),
        ),
    ]
