# Generated by Django 3.2.22 on 2023-10-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mood_emoji',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
